import React,{useState}from"react";import{createRoot}from"react-dom/client";import{ArrowUpRight,Menu,X,Phone,MessageCircle,MapPin,Check,Building2,House,RefreshCw,Layers3}from"lucide-react";import"./styles.css";
const phone="919620484545";
const projects=[
["Modern Residence","Residential · Mysuru","https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1500&q=88"],
["Contemporary Villa","Residential · Karnataka","https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1500&q=88"],
["Commercial Space","Commercial · Mysuru","https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1500&q=88"],
["Premium Home","Residential · Karnataka","https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1500&q=88"]
];
const services=[
[House,"Residential Construction","Thoughtfully planned homes built around your requirements and vision."],
[Building2,"Commercial Construction","Reliable construction solutions for commercial spaces and developments."],
[RefreshCw,"Renovation & Remodeling","Modernising existing spaces with practical planning and quality finishes."],
[Layers3,"Turnkey Construction","A streamlined approach from planning and execution through handover."]
];
function App(){const[open,setOpen]=useState(false);const go=id=>{document.getElementById(id)?.scrollIntoView({behavior:"smooth"});setOpen(false)};return <div className="site"><div className="demo">CONCEPT WEBSITE · DEMO</div><header><a className="logo" href="#home"><span className="diamond">◆</span><span><b>SWAMI VIVEKANANDA</b><small>CONSTRUCTIONS</small></span></a><nav className={open?"open":""}>{["home","about","services","projects","contact"].map(x=><button key={x} onClick={()=>go(x)}>{x}</button>)}<button className="navcta" onClick={()=>go("contact")}>Enquire <ArrowUpRight size={15}/></button></nav><button className="men" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></header>
<section id="home" className="hero"><div className="heroimg"/><div className="shade"/><div className="heroin"><p className="eyebrow">CONSTRUCTION · MYSURU · KARNATAKA</p><h1>Building with<br/><i>purpose.</i></h1><p className="lead">Thoughtful construction solutions for homes and spaces built to last.</p><div className="actions"><button className="gold" onClick={()=>go("projects")}>Explore Our Work <ArrowUpRight size={18}/></button><button className="outline" onClick={()=>go("contact")}>Talk to Us</button></div></div><div className="scroll">SCROLL <span/></div></section>
<section id="about" className="section about"><div className="label">01 / ABOUT</div><div className="grid2"><div><p className="eyebrow dark">SWAMI VIVEKANANDA CONSTRUCTIONS</p><h2>Built around <i>quality.</i><br/>Designed for life.</h2></div><div className="copy"><p>Swami Vivekananda Constructions is a Mysuru-based construction and building-services business. This concept website presents a clean, premium way to showcase the company, its capabilities and its work to prospective customers.</p><p>From planning and construction to finishing, every project deserves clear communication and dependable execution.</p><button className="link" onClick={()=>go("contact")}>Discuss your project <ArrowUpRight size={17}/></button></div></div><div className="trust"><div><b>4.9★</b><span>Google rating*</span></div><div><b>237+</b><span>Public ratings*</span></div><div><b>Mysuru</b><span>Local presence</span></div></div><small className="note">*Public Google Business Profile figures checked for this demo; ratings/review counts can change.</small></section>
<section id="services" className="section services"><div className="label">02 / SERVICES</div><p className="eyebrow dark">WHAT WE DO</p><h2>Construction that <i>fits your vision.</i></h2><div className="servicegrid">{services.map(([Icon,title,text],i)=><article key={title}><span className="num">0{i+1}</span><Icon size={29} strokeWidth={1.4}/><h3>{title}</h3><p>{text}</p><ArrowUpRight className="arr" size={18}/></article>)}</div></section>
<section id="projects" className="section projects"><div className="label">03 / SELECTED WORK</div><div className="projecthead"><div><p className="eyebrow dark">A GLIMPSE OF THE POSSIBILITIES</p><h2>Spaces worth <i>remembering.</i></h2></div><p>Sample imagery is used in this pitch demo. It can be replaced with Swami Vivekananda's verified project photographs after approval.</p></div><div className="projectgrid">{projects.map((p,i)=><article className={i===0?"featured":""} key={p[0]}><img src={p[2]} alt={p[0]}/><div className="pshade"/><div className="ptext"><small>{p[1]}</small><h3>{p[0]}</h3></div><span className="parr"><ArrowUpRight size={19}/></span></article>)}</div></section>
<section className="why"><div className="whyimg"/><div className="whyin"><div className="label light">04 / WHY SWAMI VIVEKANANDA</div><p className="eyebrow">THE DETAILS MATTER</p><h2>Confidence from<br/><i>start to finish.</i></h2><div className="list">{[["Quality workmanship","Attention to materials, detailing and finishing."],["Clear communication","Straightforward updates throughout the project."],["Practical execution","A structured approach to keeping work moving."],["Built for the long term","Spaces designed for everyday life and lasting value."]].map(x=><div><span><Check size={15}/></span><p><b>{x[0]}</b><small>{x[1]}</small></p></div>)}</div></div></section>
<section id="contact" className="contact section"><p className="eyebrow">START A CONVERSATION</p><h2>Let's build<br/><i>something meaningful.</i></h2><p>Have a home or construction project in mind? Get in touch with Swami Vivekananda Constructions.</p><div className="contactbuttons"><a href={"tel:+"+phone}><Phone size={18}/> Call Now</a><a className="wa" href={"https://wa.me/"+phone}><MessageCircle size={18}/> WhatsApp</a></div><div className="meta"><span><MapPin size={16}/> KD Circle, Manchegowdana Koppalu, Vijayanagar 2nd Stage, Mysuru 570017</span><span>+91 96204 84545</span></div></section>
<footer><div className="logo"><span className="diamond">◆</span><span><b>SWAMI VIVEKANANDA</b><small>CONSTRUCTIONS</small></span></div><p>© 2026 Swami Vivekananda Constructions · Concept website demo</p></footer><a className="floatwa" href={"https://wa.me/"+phone}><MessageCircle size={22}/></a></div>}createRoot(document.getElementById("root")).render(<App/>);